[project]
name = "studentscoreai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-api-python-client>=2.194.0",
    "langchain>=1.2.15",
    "langchain-classic>=1.0.3",
    "langchain-openai>=1.1.12",
    "openai-whisper>=20250625",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.2",
]
